language: node_js
node_js: node
services: mongodb
deploy:
  provider: heroku
  api_key:
    secure: J4s4ZCTTqYojlWng80WIeEGTIDRBs/jvUXhE9k0XJ49hFckO/68GSh7PSnSz207Lvype1VopZVD0HsQc2xCVZa2VUyu5OtK6MZayOYjucEPudDs8wZEtafc0Pyc5ixIOYnw6ZBqy1uA+yRV/oMaa9rk8Zt4mQW4b+/n1AE4W5DyqiGz8R3zl8ISWRaoXwOWq+sv3Tf+UbWaLEDU52tiDtuwCSGa/K90pDesrvdv/HgAua/cWnwQRCMjkkfBgj826pwvDYyOyqASb9iUSqU4C35UgDBJPv5XNyKCzWmqnVemqE50fLrHpatI8NbX2kTo9ft6CE3V02wvlKZ/hVse9g0SyuKn/tCkdK1NNiJsUn+Sfx4iad6h3vMq2rFjhmgTTyFNozean5rZDc/wm2Vtn/I/NfXWXFvDWkO5wKoNNEB8ZluxyJM0u4chVmsm3CWHzOCpJLd2ri+HPIDtAwXBh4BNtPMUZhElgB0acdfZhWYHM3FOPVnKaiPN7dQP1irSxR1UfRTNwXwjXCOHd4JYILEXipFBidxwgkQTMoJSkJ7uoalS5pEC1KqFECTJU8RQLcRxgNwVCHrAwPamYtKWUuarQIwvUOD+Iguw9DDStN1CwoFCftZVXwuoeLWQf4mwKBTJsT7WWuY//iqUNA49mM4HGf/RVA7IaKlaIClsBCCY=
  app: mysterious-mountain-90340
  on:
    repo: maripal/node-capstone-tasks
    branch: feature/layout-and-css
