language: node_js
node_js: node
services: mongodb
deploy:
  provider: heroku
  api_key:
    secure: NmdmacNTVcw3Se3ufAaST4lW/OoAP3qD65pX8GJmsMA1gJQZZm7k7/m12YDGTMmpMRPXLemZ3GNFKtyksYR0vnUI69riMZMLp+WHe3+CzuXQjKzKEM6y406KvEEdmsiRy2rFxJVNfF/BKa2XaxAEH10agN4AtKaUcs77tIsALf6fivAq3kqmi2xto+yv1ZTPS/zehCJ6LmbK9CzWD+sIVZIFOgwz8CDQCJ/eUnyePne8VOwLbITXMIaFBhZvSpbttGzIkNzHWGBLn10G7LIMjpwsEaQbwIqXGPF1xZibqWag2bAwQ+apFKnPctIWKKLktfojlmtxx1wWRMxjvYmM1l6hUalYTqw6IWswr2YREQ0q57PSbU34U9vclJsYY16vo5upFC0ZaZn4EY+SKzGvi1q6FxkPcF5qHmclokb5TqJ0cywDQ9VjuLWAPKlqMckif5TVFmKcqwdT3nWuwbgE0eA4Bv/G3ToMde+erBCQDNSXiIL4lWnoN8gB108s10Oip3mMv+5waFnmfBfQeyFhn8O0NOs3/gIcvxmrK2z5Zz6TBkW/WvjpLgSwiSXmQiGqbYfHkW3gXaziozJTgAtG5Fy0lkROGAlyho5JZMmmCxfGSvm3XqXWCPwl3tCn9syfVsLaoHtTuotaS+Dw4zwJ1gQPOWhRnLf+t2uxz5CEAmI=
  app: dry-tor-94424
  on:
    repo: maripal/node-capstone-tasks
