language: node_js
node_js: node
services: mongodb
deploy:
  provider: heroku
  api_key:
    secure: WitoEmfzeQf5nX9zHNRJnDJwmXTyAcoe2tH6RfHkovjpXTEUDiXlMokNTfgo7ogwz4dVZHhM8v0wncyP2IX9d/LoFR/T47Y6/nuM1McksnrtQTPJbwVY8jSvMTSilL4GagYh3HNENUKcxFMPKTw5DktUo1AesrzGEv24CF2StyEP+XB3FpY8GEN1obGHPMb4vVUOVt2xq3L3XsJuF0thTYyhJihJB1O5kV7GAdkkfJM+RiSWxfO8FvfYDUA5lOtvjUP3kruaA2OhRZDCkTWRzh/Uwi2wjvaYjCybE13607DCs47VWBdMTCB7dNyVORb5wHM2ikYs2PEn5W6/tdG5TGKoDX6QdZKkoR6fBFr4N0UoRHITWKQrCYoUluoKkBYF0p5VYkikro4sRhg/kM/S32DrfwxZn3LAP6BewAXMsJ2S2J3aZS1oDmaClVwmwZZBccBkZNkZ/sifeZ9oChbCW/oQxayDVCdpHAYw10JICs3XvtXJPPKHHyBLO481LW86Gsp+MidQThP6NnqD0q7Kfks1Jh7wJKR/4RyLmQBwEzoK15mxOYUusOFMzO4tKjQpfo/YV3uxcKZIlfd1wx/VfZ2XZ6Zk1MeK1tqh0g6Nymy39TZpKio7xEw5fOhaeCsALkyfybHSDoSsho27ZU2mbGgzGevoM/Wkg4oU3IHzqqw=
  app: gentle-wave-35225
  on:
    repo: maripal/node-capstone-tasks
