language: node_js
node_js: node
services: mongodb
deploy:
  provider: heroku
  api_key:
    secure: RBO1KgzFe46hjiE0L4GZeysgWdc3QGdGaYbU99PjcHph6CWV6/ht7eAXaRHu7pdmur9nrjUI3gdg/pXc/jmOHPzP7QIBZPQTcstqPtFPD/zXoK1BGpYYTrad4jaFPjF5z7sapjwFYcDV8DbI5dCXZoeplkWcIUeofmASMPnSyYHAAAVL1lcHBHdKP+BJA+3IkeiIqKisGt42eYW1Y0SkjvUgeowLUr8e0wLdN2WyHyVWJmwcLcSHmZh+rKskv9oDt8NKJmtsGdBdYb3ccun5V6EUm8RjOut7LE+nRDTutdqzx7+W9CK8HgicciyvVQP2Ll7Z2b4RD2dC/nrNki8PfmiPVJRY9fGbcE3HGVHhY/4HdGxDLZgX6plw3NmeH2VUCbgTzAA0DEvrXJQpvLEJldGUhDMnEgd35B4gKgilcT3j+vU4TLA81xwJponGys260IvdYek5vR5+DAvW2iQXEqCHDpo1oaDaynelsf3AUB3ls7GTE9KpZMcb4P/emeaKatR1MCCU9t8Yc3E4qKASisc0je3BFICGk+DuBPnKA0i5DLRuGbegN6p6rT54gl9LC9N12LmIaQvq/a834OGTmp4MvyoZTtz81RfBHLxoluuGyKZA5bVhs9uiRCMPUOvTi7w43mvDuETO7txtc3Jk1GWCRdTRQLpKCV1WXs9q7RE=
  app: gentle-wave-35225
  on:
    repo: maripal/node-capstone-tasks

